"use client"

import { useSearchParams } from 'next/navigation'
import { useEffect } from 'react'

export default function PrintableBonafide() {
  const searchParams = useSearchParams()
  const regNo = searchParams.get('reg') || "3576"
  const session = searchParams.get('session') || "2026-27"
  const purpose = searchParams.get('purpose') || "SELF"
  
  // Generating logic for CACS reference based on rules
  const issueYear = session.split('-')[0]
  const autoGeneratedRef = `CACS/${issueYear}/188`
  const issueDate = "28/03/2026"

  useEffect(() => {
    // Optionally auto-trigger print dialog when component mounts fully
    // window.print();
  }, [])

  return (
    <div className="w-full bg-slate-200 min-h-screen py-8 print:bg-white print:py-0">
      
      {/* Floating Action Menu Header (Hidden when printing via CSS @media print) */}
      <div className="max-w-[800px] mx-auto mb-4 bg-white p-3 rounded shadow-md border flex gap-3 print:hidden justify-end">
        <button onClick={() => window.print()} className="bg-blue-600 text-white font-bold px-4 py-2 rounded text-sm hover:bg-blue-700 shadow flex items-center gap-2">
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 6 2 18 2 18 9"></polyline><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path><rect x="6" y="14" width="12" height="8"></rect></svg>
           Print / Save as PDF
        </button>
        <button onClick={() => window.close()} className="bg-slate-200 text-slate-800 font-bold px-4 py-2 rounded text-sm hover:bg-slate-300 shadow">
           Close Tab
        </button>
      </div>

      {/* Printable Area - A4 Paper Sizing wrapper */}
      <div className="max-w-[800px] mx-auto bg-white min-h-[1100px] p-12 shadow-xl border print:shadow-none print:border-none print:p-0">
        
        {/* School Header Structure */}
        <div className="flex gap-6 items-center mb-6">
           {/* Logo Placeholder */}
           <div className="w-32 h-32 flex shrink-0 items-center justify-center p-2">
              <div className="w-full h-full rounded-full border-4 border-dashed border-[#000080] flex items-center justify-center text-xs text-[#000080] font-bold text-center bg-blue-50 relative">
                 <div className="absolute top-0 w-full text-center text-[8px] mt-1 curve-text">CHILDREN'S ACADEMY</div>
                 <div className="absolute bottom-2">ALWAR</div>
              </div>
           </div>

           {/* Institution Text */}
           <div className="flex flex-col">
              <h1 className="text-3xl font-serif font-bold text-black uppercase tracking-tight leading-tight">CHILDREN'S ACADEMY CONVENT SCHOOL</h1>
              <p className="font-serif mt-2 text-md">DELHI ROAD, DIWAKRI, ALWAR- 301001 (RAJ.)</p>
              <p className="font-serif mt-1 text-md text-blue-800">www.cacsalw.com; childrenacademy7@rediffmail.com</p>
              <p className="font-serif mt-1 font-semibold text-md">Call Us: 9461230218, 0144-3249344</p>
           </div>
        </div>

        <div className="w-full border-t-4 border-black mb-1"></div>
        <div className="w-full border-t border-black mb-3"></div>

        {/* Dynamic Meta Headers */}
        <div className="flex justify-between items-center mb-3">
           <h3 className="font-serif font-bold text-xl">Ref. No : <span className="font-sans font-medium">{autoGeneratedRef}</span></h3>
           <h3 className="font-serif font-bold text-xl">Date : <span className="font-sans font-medium">{issueDate}</span></h3>
        </div>

        <div className="w-full border-b-4 border-black mb-1"></div>
        <div className="w-full border-b border-black mb-12"></div>

        {/* Certificate Title */}
        <h2 className="text-3xl font-sans font-bold text-center mb-10 tracking-widest uppercase underline decoration-2 underline-offset-8">
           BONAFIDE CERTIFICATE
        </h2>

        {/* Student Photo */}
        <div className="flex justify-center mb-12">
           <div className="w-[140px] h-[170px] border border-slate-300 bg-yellow-50 flex items-center justify-center relative overflow-hidden">
               <span className="text-slate-400 font-medium text-sm absolute">Photo Placed Here</span>
               <div className="absolute bottom-0 w-full bg-black/5 h-8"></div>
           </div>
        </div>

        {/* Body Content - Procedural text generation */}
        <div className="px-8 leading-loose text-lg font-serif space-y-6 text-justify">
           <p>
             This is to certify that Master/Miss <span className="font-bold border-b border-dotted border-black min-w-[300px] inline-block text-center uppercase">DEVISH KUMAR</span>
           </p>
           <p>
             Son/Daughter of <span className="font-bold border-b border-dotted border-black min-w-[200px] inline-block text-center">Mr. MAHESH CHAND BAIRWA</span> &amp; 
             <span className="font-bold border-b border-dotted border-black min-w-[200px] inline-block text-center">Mrs. BAIRWA</span>
           </p>
           <p>
             is a bonafide student of this school in Class <span className="font-bold border-b border-dotted border-black min-w-[100px] inline-block text-center">I</span>, Section <span className="font-bold border-b border-dotted border-black min-w-[100px] inline-block text-center">A</span>
           </p>
           <p>
             during the academic session <span className="font-bold border-b border-dotted border-black min-w-[150px] inline-block text-center">{session}</span>.
           </p>
           
           <br/>
           <br/>
           <p>This certificate is issued on request for the purpose of: <span className="font-bold border-b border-dotted border-black px-4">{purpose}</span>.</p>
        </div>

        <br/><br/><br/><br/>
        {/* Signatures */}
        <div className="flex justify-between px-8 text-lg font-serif font-bold mt-12">
           <div className="flex flex-col items-center">
              <span className="block h-12"></span>
              <span>Class Teacher</span>
           </div>
           
           <div className="flex flex-col items-center">
              <span className="block h-12"></span>
              <span>Principal Signature</span>
           </div>
        </div>

      </div>

    </div>
  )
}
